# Generated by Django 3.2 on 2022-09-28 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RealtType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='тип недвижимости')),
            ],
            options={
                'verbose_name': 'Тип недвижимости',
                'verbose_name_plural': 'Тип недвижимости',
            },
        ),
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, upload_to='media/', verbose_name='Изображение1')),
                ('image2', models.ImageField(blank=True, upload_to='media/', verbose_name='Изображение2')),
                ('image3', models.ImageField(blank=True, upload_to='media/', verbose_name='Изображение3')),
                ('image4', models.ImageField(blank=True, upload_to='media/', verbose_name='Изображение4')),
                ('image5', models.ImageField(blank=True, upload_to='media/', verbose_name='Изображение5')),
                ('image6', models.ImageField(blank=True, upload_to='media/', verbose_name='Изображение6')),
                ('description', models.CharField(max_length=4000, verbose_name='Описание')),
                ('overall_size', models.DecimalField(decimal_places=5, max_digits=10000)),
                ('residential_size', models.DecimalField(decimal_places=5, max_digits=10000)),
                ('kitchen_size', models.DecimalField(decimal_places=5, max_digits=10000)),
                ('number_of_rooms', models.DecimalField(decimal_places=3, max_digits=10)),
                ('floor', models.DecimalField(decimal_places=3, max_digits=10)),
                ('number_of_building', models.DecimalField(decimal_places=3, max_digits=10)),
                ('building_freshness', models.CharField(choices=[('ВТОРИЧКА', 'новое здание'), ('НОВОЕ', 'вторичная недвижимость')], max_length=20)),
                ('title', models.CharField(max_length=40, verbose_name='Заголовок')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('contacts', models.TextField(verbose_name='Контакты')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Выводить в списке?')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор объявления')),
                ('realt_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='advert.realttype', verbose_name='Рубрика')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-created_at'],
            },
        ),
    ]
